#!/usr/bin/env bash
set -euo pipefail

REMOTE_HOST="${REMOTE_HOST:-services-vm}"
REMOTE_OLLAMA_PORT="${REMOTE_OLLAMA_PORT:-22134}"
REMOTE_TTS_PORT="${REMOTE_TTS_PORT:-22880}"
LOCAL_OLLAMA_HOST="${LOCAL_OLLAMA_HOST:-127.0.0.1}"
LOCAL_OLLAMA_PORT="${LOCAL_OLLAMA_PORT:-11434}"
LOCAL_TTS_HOST="${LOCAL_TTS_HOST:-127.0.0.1}"
LOCAL_TTS_PORT="${LOCAL_TTS_PORT:-8880}"

exec ssh \
  -NT \
  -o ExitOnForwardFailure=yes \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  -R "127.0.0.1:${REMOTE_OLLAMA_PORT}:${LOCAL_OLLAMA_HOST}:${LOCAL_OLLAMA_PORT}" \
  -R "127.0.0.1:${REMOTE_TTS_PORT}:${LOCAL_TTS_HOST}:${LOCAL_TTS_PORT}" \
  "${REMOTE_HOST}"
